# Generated by Django 3.1 on 2020-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=30)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
    ]
