# Generated by Django 3.1 on 2020-08-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoah', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
